//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResxTranslator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResxTranslator.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t close at this time.
        /// </summary>
        internal static string Error_CantClose {
            get {
                return ResourceManager.GetString("Error_CantClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string Error_DirectoryMissing {
            get {
                return ResourceManager.GetString("Error_DirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate resource file: {0}.
        /// </summary>
        internal static string Error_DuplicateResx {
            get {
                return ResourceManager.GetString("Error_DuplicateResx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while saving: {0}.
        /// </summary>
        internal static string Error_FailedSaving {
            get {
                return ResourceManager.GetString("Error_FailedSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid command line 
        ///{0}
        ///Path: {1}.
        /// </summary>
        internal static string Error_InvalidCommandLine {
            get {
                return ResourceManager.GetString("Error_InvalidCommandLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key name can only contain letters and numbers.
        /// </summary>
        internal static string Error_InvalidKeyName {
            get {
                return ResourceManager.GetString("Error_InvalidKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key with this name already exists.
        /// </summary>
        internal static string Error_KeyAlreadyExists {
            get {
                return ResourceManager.GetString("Error_KeyAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key name can&apos;t be empty.
        /// </summary>
        internal static string Error_KeyCantBeEmpty {
            get {
                return ResourceManager.GetString("Error_KeyCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string LoadProgress_Done {
            get {
                return ResourceManager.GetString("LoadProgress_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading resources....
        /// </summary>
        internal static string LoadProgress_LoadingResources {
            get {
                return ResourceManager.GetString("LoadProgress_LoadingResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening &quot;{0}&quot;....
        /// </summary>
        internal static string LoadProgress_OpeningDirectory {
            get {
                return ResourceManager.GetString("LoadProgress_OpeningDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading reference assemblies....
        /// </summary>
        internal static string LoadProgress_ReferenceAssemblies {
            get {
                return ResourceManager.GetString("LoadProgress_ReferenceAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No resource loaded.
        /// </summary>
        internal static string MainWindow_CurrentResource_NoResourceLoaded {
            get {
                return ResourceManager.GetString("MainWindow_CurrentResource_NoResourceLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new row.
        /// </summary>
        internal static string MainWindow_FailedToCreateANewRow {
            get {
                return ResourceManager.GetString("MainWindow_Failed_to_create_a_new_row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More languages....
        /// </summary>
        internal static string MainWindow_MoreLanguagesMenuItem {
            get {
                return ResourceManager.GetString("MainWindow_MoreLanguagesMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse to the root of the project, typically where the sln file is..
        /// </summary>
        internal static string MainWindow_OpenDirectory_Description {
            get {
                return ResourceManager.GetString("MainWindow_OpenDirectory_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the currently selected row?.
        /// </summary>
        internal static string MessageBox_ConfirmDeleteRow_Message {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmDeleteRow_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a key.
        /// </summary>
        internal static string MessageBox_ConfirmDeleteRow_Title {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmDeleteRow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With current settings this operation will try to load {0} assemblies. Do you really want to load them all? If you select no, loading will be skipped..
        /// </summary>
        internal static string MessageBox_ConfirmLoadAssemblies_Message {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmLoadAssemblies_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load reference assemblies.
        /// </summary>
        internal static string MessageBox_ConfirmLoadAssemblies_Title {
            get {
                return ResourceManager.GetString("MessageBox_ConfirmLoadAssemblies_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource file for this language is missing, do you want to create it?.
        /// </summary>
        internal static string MessageBox_CreateMissingResource_Message {
            get {
                return ResourceManager.GetString("MessageBox_CreateMissingResource_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing resource file.
        /// </summary>
        internal static string MessageBox_CreateMissingResource_Title {
            get {
                return ResourceManager.GetString("MessageBox_CreateMissingResource_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will remove everything that is not text from translated resources (not the base resource). Resources will be saved to the drive in process, so make sure you have a backup..
        /// </summary>
        internal static string MessageBox_RemoveNontranslatableQuestion_Message {
            get {
                return ResourceManager.GetString("MessageBox_RemoveNontranslatableQuestion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove non-translatable data?.
        /// </summary>
        internal static string MessageBox_RemoveNontranslatableQuestion_Title {
            get {
                return ResourceManager.GetString("MessageBox_RemoveNontranslatableQuestion_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want save your changes before closing?.
        /// </summary>
        internal static string MessageBox_SaveChangesBeforeClose_Message {
            get {
                return ResourceManager.GetString("MessageBox_SaveChangesBeforeClose_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        internal static string MessageBox_SaveChangesBeforeClose_Title {
            get {
                return ResourceManager.GetString("MessageBox_SaveChangesBeforeClose_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected language is invalid, please select one of the entries on the dropdown list..
        /// </summary>
        internal static string MessageBox_SelectedLanguageInvalid_Message {
            get {
                return ResourceManager.GetString("MessageBox_SelectedLanguageInvalid_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid language.
        /// </summary>
        internal static string MessageBox_SelectedLanguageInvalid_Title {
            get {
                return ResourceManager.GetString("MessageBox_SelectedLanguageInvalid_Title", resourceCulture);
            }
        }
    }
}
